---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sig-8-depl
  labels:
    app: devops-sig-8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-sig-8
  template:
    metadata:
      labels:
        app: devops-sig-8
    spec:
      shareProcessNamespace: true
      volumes:
        - name: devops-sig-8-vol
          configMap:
            name: devops-sig-8-configmap
      terminationGracePeriodSeconds: 60  # gunicorn has 30s graceful exit by default
      containers:
        - name: app
          image: "kaszpir/devops-sig-8:73c27beb2d781447b7534cf189ecf0fc3636b413"
          imagePullPolicy: Always
          env:
            - name: GUNICORN_CMD_ARGS
              value: '--graceful-timeout=10 --timeout=15'
          ports:
            - name: app
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /const
              port: 8000
            timeoutSeconds: 5
            periodSeconds: 2
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /const
              port: 8000
            timeoutSeconds: 5
            periodSeconds: 2
            initialDelaySeconds: 10
          volumeMounts:
            - name: devops-sig-8-vol
              mountPath: /etc/app/
          lifecycle:
            preStop:
              exec:
                # graceful shutdown of gunicorn (actually all processes)
                command: ["/bin/sh", "-c", "killall5 -15;sleep 10;"]

        - name: watcher
          image: "kaszpir/devops-sig-8-watcher:73c27beb2d781447b7534cf189ecf0fc3636b413"
          imagePullPolicy: Always
          volumeMounts:
            - name: devops-sig-8-vol
              mountPath: /etc/app/
