---
apiVersion: v1
kind: Service
metadata:
  name: devops-sig-8
  labels:
    app: devops-sig-8
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: web
  selector:
    app: devops-sig-8
